from __future__ import annotations

from typing import Protocol

from app.domain.influencer import Influencer, InfluencerContent


class InfluencerRepository(Protocol):
    async def list(self) -> list[Influencer]: ...

    async def get(self, influencer_id: int) -> Influencer | None: ...

    async def find_by_name(self, name: str) -> Influencer | None: ...

    async def create(self, influencer: Influencer) -> Influencer: ...

    async def update(self, influencer: Influencer) -> Influencer: ...

    async def add_content(self, content: InfluencerContent) -> InfluencerContent: ...

    async def list_contents(self, influencer_id: int) -> list[InfluencerContent]: ...
