from typing import Protocol

from app.domain.social_creator import SocialCreator


class SocialCreatorRepository(Protocol):
    async def list(self) -> list[SocialCreator]: ...

    async def find_by_id(self, creator_id: int) -> SocialCreator | None: ...

    async def find_by_name(self, name: str) -> SocialCreator | None: ...

    async def create(self, item: SocialCreator) -> SocialCreator: ...

    async def update(self, item: SocialCreator) -> SocialCreator: ...
